export const PokemonsList = [
    {
        id: "#001",
        name: "Bulbasaur",
        img_src: "https://cdn.bulbagarden.net/upload/thumb/2/21/001Bulbasaur.png/250px-001Bulbasaur.png",
        url: "bulbasaur#001",
        type: "Grass, Poison",
        max_cp: "1115",
        attack: "118",
        defense: "111",
        stamina: "128",
        weakness: "Fire, Flying, Ice, Psychic"
    },
    {
        id: "#002",
        name: "Ivysaur",
        img_src: "https://cdn.bulbagarden.net/upload/thumb/7/73/002Ivysaur.png/250px-002Ivysaur.png",
        url: "ivysaur#002",
        type: "Grass, Poison",
        max_cp: "1699",
        attack: "151",
        defense: "141",
        stamina: "155",
        weakness: "Fire, Flying, Ice, Psychic"
    },
    {
        id: "#003",
        name: "Venusaur",
        img_src: "https://cdn.bulbagarden.net/upload/thumb/a/ae/003Venusaur.png/250px-003Venusaur.png",
        url: "venusaur#003",
        type: "Grass, Poison",
        max_cp: "2720",
        attack: "198",
        defense: "189",
        stamina: "190",
        weakness: "Fire, Flying, Ice, Psychic"
    },
    {
        id: "#004",
        name: "Charmander",
        img_src: "https://cdn.bulbagarden.net/upload/thumb/7/73/004Charmander.png/250px-004Charmander.png",
        url: "charmander#004",
        type: "Fire",
        max_cp: "980",
        attack: "116",
        defense: "93",
        stamina: "118",
        weakness: "Ground, Rock, Water"
    },
    {
        id: "#005",
        name: "Charmeleon",
        img_src: "https://cdn.bulbagarden.net/upload/thumb/4/4a/005Charmeleon.png/250px-005Charmeleon.png",
        url: "charmeleon#005",
        type: "Fire",
        max_cp: "1653",
        attack: "158",
        defense: "126",
        stamina: "151",
        weakness: "Ground, Rock, Water"
    },
    {
        id: "#006",
        name: "Charizard",
        img_src: "https://cdn.bulbagarden.net/upload/thumb/7/7e/006Charizard.png/250px-006Charizard.png",
        url: "charizard#006",
        type: "Fire, Flying",
        max_cp: "2889",
        attack: "223",
        defense: "173",
        stamina: "186",
        weakness: "Rock, Electric, Water"
    },
    {
        id: "#007",
        name: "Squirtle",
        img_src: "https://cdn.bulbagarden.net/upload/thumb/3/39/007Squirtle.png/250px-007Squirtle.png",
        url: "squirtle#007",
        type: "Water",
        max_cp: "946",
        attack: "94",
        defense: "121",
        stamina: "127",
        weakness: "Electric, Grass"
    },
    {
        id: "#008",
        name: "Wartortle",
        img_src: "https://cdn.bulbagarden.net/upload/thumb/0/0c/008Wartortle.png/250px-008Wartortle.png",
        url: "wartortle#008",
        type: "Water",
        max_cp: "1488",
        attack: "126",
        defense: "155",
        stamina: "153",
        weakness: "Electric, Grass"
    },
    {
        id: "#009",
        name: "Blastoise",
        img_src: "https://cdn.bulbagarden.net/upload/thumb/0/02/009Blastoise.png/250px-009Blastoise.png",
        url: "blastoise#009",
        type: "Water",
        max_cp: "2466",
        attack: "171",
        defense: "207",
        stamina: "188",
        weakness: "Electric, Grass"
    },
    {
        id: "#010",
        name: "Caterpie",
        img_src: "https://cdn.bulbagarden.net/upload/thumb/5/5d/010Caterpie.png/250px-010Caterpie.png",
        url: "caterpie#010",
        type: "Bug",
        max_cp: "437",
        attack: "55",
        defense: "55",
        stamina: "128",
        weakness: "Fire, Flying, Rock"
    },
    {
        id: "#011",
        name: "Metapod",
        img_src: "https://cdn.bulbagarden.net/upload/thumb/c/cd/011Metapod.png/250px-011Metapod.png",
        url: "metapod#011",
        type: "Bug",
        max_cp: "450",
        attack: "45",
        defense: "80",
        stamina: "137",
        weakness: "Fire, Flying, Rock"
    },
    {
        id: "#012",
        name: "Butterfree",
        img_src: "https://cdn.bulbagarden.net/upload/thumb/d/d1/012Butterfree.png/250px-012Butterfree.png",
        url: "butterfree#012",
        type: "Bug, Flying",
        max_cp: "1827",
        attack: "167",
        defense: "137",
        stamina: "155",
        weakness: "Fire, Flying, Rock, Electric, Ice"
    },
    {
        id: "#013",
        name: "Weedle",
        img_src: "https://cdn.bulbagarden.net/upload/thumb/d/df/013Weedle.png/250px-013Weedle.png",
        url: "weedle#013",
        type: "Bug, Poison",
        max_cp: "456",
        attack: "63",
        defense: "50",
        stamina: "120",
        weakness: "Fire, Flying, Rock, Psychic"
    },
    {
        id: "#014",
        name: "Kakuna",
        img_src: "https://cdn.bulbagarden.net/upload/thumb/f/f0/014Kakuna.png/250px-014Kakuna.png",
        url: "kakuna#014",
        type: "Bug, Poison",
        max_cp: "432",
        attack: "46",
        defense: "75",
        stamina: "128",
        weakness: "Fire, Flying, Rock, Psychic"
    },
    {
        id: "#015",
        name: "Beedrill",
        img_src: "https://cdn.bulbagarden.net/upload/thumb/6/61/015Beedrill.png/250px-015Beedrill.png",
        url: "beedrill#015",
        type: "Bug, Poison",
        max_cp: "1846",
        attack: "169",
        defense: "130",
        stamina: "163",
        weakness: "Fire, Flying, Rock, Psychic"
    },
    {
        id: "#016",
        name: "Pidgey",
        img_src: "https://cdn.bulbagarden.net/upload/thumb/5/55/016Pidgey.png/250px-016Pidgey.png",
        url: "pidgey#016",
        type: "Normal, Flying",
        max_cp: "680",
        attack: "85",
        defense: "73",
        stamina: "120",
        weakness: "Electric, Ice, Rock"
    }
]